[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
# IMPORTANT: the -T… flag is now provided by build.rs, so we remove it here.
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-static",
    "-C", "link-arg=-no-pie",
]

# Use the system GNU linker explicitly (works great for this bare-metal target).
# If you prefer LLD and have it installed, you can use: linker = "ld.lld"
linker = "x86_64-linux-gnu-ld"
