[workspace]
members = [
    "rtos-bootloader",
    "rtos-kernel",
    "rtos",
    "libs/rtkfmt",
    "libs/hal",
    "libs/vfs",
    "libs/rtkfmt",
    "drivers/virtio-blk",
    "file-systems/fat32",
    "tools/rtkgen"
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
