[package]
name = "rtos-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.35", default-features = false }
panic-abort = "0.3.2"

[[bin]]
name = "kernelx64"
path = "src/main.rs"
test = false
doctest = false
bench = false
